from house.furniture.x import X
from house.furniture.Medeb import Bed
from house.furniture.sefed import Tv
from house.furniture.clothse import Armario
from house.furniture.mitad import Fogao
from house.furniture.chairs import Chairs
from house.furniture.base_furniture import BaseFurniture
from  house.furniture.table import Fogao1
from  house.furniture.gebeta import Gebeta
from  house.furniture.skinmedeb import skinmedeb
from  house.furniture.wefcho import Kidan
from  house.furniture.wefchouse import Wefcho
from  house.furniture.clothse2 import cloth
from  house.furniture.stone import Stone